version: "2"

linters:
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true
        - name: exported
          disabled: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
