syntax = "proto3";

package orbit.v1.project;


message ProjectResp {
  string id = 1;
  string name = 2;
  string code = 3;
  bool is_active = 4;
  string created_at = 5;
  string updated_at = 6;
}

message ProjectMemberResp {
  string id = 1;
  string username = 2;
  optional string email = 3;
  string status = 4;
  string auth_source = 5;
  optional string last_login_at = 6;
}

message ProjectListResp {
  repeated ProjectResp items = 1;
}

message ProjectMemberListResp {
  repeated ProjectMemberResp items = 1;
}

message ProjectSaveReq {
  string name = 1;
  string code = 2;
}

message ProjectMemberReq {
  string user_id = 1;
}

message ProjectDeprecateReq {}
