// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config_file.sql

package sqlc

import (
	"context"
)

const configFileByID = `-- name: ConfigFileByID :one
SELECT id, application_id, path, content, created_at, updated_at
FROM application_config_file
WHERE id = ?
`

func (q *Queries) ConfigFileByID(ctx context.Context, id string) (ApplicationConfigFile, error) {
	row := q.db.QueryRowContext(ctx, configFileByID, id)
	var i ApplicationConfigFile
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Path,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const configFilesByApplication = `-- name: ConfigFilesByApplication :many
SELECT id, application_id, path, content, created_at, updated_at
FROM application_config_file
WHERE application_id = ?
ORDER BY path
`

func (q *Queries) ConfigFilesByApplication(ctx context.Context, applicationID string) ([]ApplicationConfigFile, error) {
	rows, err := q.db.QueryContext(ctx, configFilesByApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationConfigFile
	for rows.Next() {
		var i ApplicationConfigFile
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Path,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteConfigFile = `-- name: DeleteConfigFile :exec
DELETE FROM application_config_file
WHERE id = ?
`

func (q *Queries) DeleteConfigFile(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteConfigFile, id)
	return err
}
