-- RAGFlow + TEI stopped initialization baseline. Generated by scripts/export_ragflow_tei_baseline.py.
PRAGMA foreign_keys = ON;
BEGIN;
INSERT OR IGNORE INTO project (id, name, code, created_at, updated_at, is_active) VALUES ('01KRRKK0K3T519ZQZES3M4QA9Z', '默认项目', 'default', '2024-03-16T00:00:00Z', '2024-03-16T00:00:00Z', 1);
INSERT INTO application (id, name, code, kind, image_pull_policy, created_at, updated_at, project_id) VALUES ('d5bukyuaictz6n3u7ewqbrh32e', 'RAGFlow', 'ragflow', 'standard', 'missing', '2026-07-29 05:43:13.6131134 +0000 UTC', '2026-07-29 05:43:13.6131134 +0000 UTC', '01KRRKK0K3T519ZQZES3M4QA9Z');
INSERT INTO application (id, name, code, kind, image_pull_policy, created_at, updated_at, project_id) VALUES ('n4gn47povet4x7vqrdq4nbiyby', 'Traefik', 'traefik', 'gateway', 'missing', '2026-07-30 06:32:13.7447493 +0000 UTC', '2026-07-30 06:32:13.7447493 +0000 UTC', '01KRRKK0K3T519ZQZES3M4QA9Z');
INSERT INTO gateway_config (application_id, rest_api_url, base_domain, image, default_entrypoint, tls_mode, created_at, updated_at) VALUES ('n4gn47povet4x7vqrdq4nbiyby', 'http://localhost:8080', 'lvh.me', 'traefik:3.6', 'web', 'none', '2026-07-30 06:32:13.7447493 +0000 UTC', '2026-07-30 06:32:13.7447493 +0000 UTC');
INSERT INTO version (id, application_id, label, status, created_from_version_id, note, component_summary, created_at, updated_at) VALUES ('ihv3kbyqegx4m4yojwpp2fqxum', 'n4gn47povet4x7vqrdq4nbiyby', 'managed-2imm5kkem7ec2krjorewk2tgk4', 'published', NULL, NULL, 'traefik', '2026-07-30 06:32:13.7447493 +0000 UTC', '2026-07-30 06:32:14.0756321 +0000 UTC');
INSERT INTO version (id, application_id, label, status, created_from_version_id, note, component_summary, created_at, updated_at) VALUES ('krq3ndmgte4mqx65uaidmeiokm', 'd5bukyuaictz6n3u7ewqbrh32e', 'ragflow-tei-cpu', 'unpublished', NULL, NULL, 'es01, minio, mysql, ragflow-cpu, redis, tei', '2026-07-29 05:44:24.4516542 +0000 UTC', '2026-07-31 04:03:24.0301992 +0000 UTC');
INSERT INTO version (id, application_id, label, status, created_from_version_id, note, component_summary, created_at, updated_at) VALUES ('mchsu5nijbna7jf4ohlkmcysxe', 'd5bukyuaictz6n3u7ewqbrh32e', 'ragflow-tei-gpu', 'unpublished', NULL, 'GPU runtime unverified', 'es01, minio, mysql, ragflow-cpu, redis, tei', '2026-07-31 03:35:10.8127922 +0000 UTC', '2026-07-31 03:35:10.8138147 +0000 UTC');
INSERT INTO version_component (id, version_id, name, image, command_json, pull_policy, restart_policy, created_at, updated_at) VALUES ('5tsyye6bkh2vzt5iqx4mrtxzeq', 'ihv3kbyqegx4m4yojwpp2fqxum', 'traefik', 'traefik:3.6', '[]', 'missing', NULL, '2026-07-30 06:32:13.7447493 +0000 UTC', '2026-07-30 06:32:13.7447493 +0000 UTC');
INSERT INTO version_component (id, version_id, name, image, command_json, pull_policy, restart_policy, created_at, updated_at) VALUES ('7epg67r6dhovu3v743hnwtxnlu', 'krq3ndmgte4mqx65uaidmeiokm', 'tei', 'ghcr.io/huggingface/text-embeddings-inference:cpu-1.9.3@sha256:ad950d30878eceb72aaf32024d26fa2b1d04a75304fa0b4776b49aa1941fea07', '["--model-id","/data/bge-m3","--json-output"]', 'missing', 'unless-stopped', '2026-07-31 03:28:40.4769771 +0000 UTC', '2026-07-31 03:29:01.0891314 +0000 UTC');
INSERT INTO version_component (id, version_id, name, image, command_json, pull_policy, restart_policy, created_at, updated_at) VALUES ('aklwuvbkrshgffcpsvvu3sa2ju', 'mchsu5nijbna7jf4ohlkmcysxe', 'es01', 'elasticsearch:8.11.3', '[]', 'missing', 'unless-stopped', '2026-07-31 03:35:10.8127922 +0000 UTC', '2026-07-31 03:35:10.8127922 +0000 UTC');
INSERT INTO version_component (id, version_id, name, image, command_json, pull_policy, restart_policy, created_at, updated_at) VALUES ('bvolgbvcokhtyqgsge4g2dfvva', 'krq3ndmgte4mqx65uaidmeiokm', 'mysql', 'mysql:8.0.39', '["--max_connections=1000","--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci","--default-authentication-plugin=mysql_native_password","--tls_version=TLSv1.2,TLSv1.3","--binlog_expire_logs_seconds=604800"]', 'missing', 'unless-stopped', '2026-07-29 05:44:24.4522011 +0000 UTC', '2026-07-31 04:03:23.9133244 +0000 UTC');
INSERT INTO version_component (id, version_id, name, image, command_json, pull_policy, restart_policy, created_at, updated_at) VALUES ('cxtiz4ny3i6e2t7s65fhl4g7rm', 'krq3ndmgte4mqx65uaidmeiokm', 'redis', 'valkey/valkey:8', '["sh","-c","exec redis-server --requirepass \"$${REDIS_PASSWORD}\" --maxmemory 128mb --maxmemory-policy allkeys-lru"]', 'missing', 'unless-stopped', '2026-07-29 05:44:24.4522011 +0000 UTC', '2026-07-31 04:03:23.9657885 +0000 UTC');
INSERT INTO version_component (id, version_id, name, image, command_json, pull_policy, restart_policy, created_at, updated_at) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'krq3ndmgte4mqx65uaidmeiokm', 'es01', 'elasticsearch:8.11.3', '[]', 'missing', 'unless-stopped', '2026-07-29 05:44:24.4522011 +0000 UTC', '2026-07-31 04:03:23.5168057 +0000 UTC');
INSERT INTO version_component (id, version_id, name, image, command_json, pull_policy, restart_policy, created_at, updated_at) VALUES ('jblgi2ezvoipwfmclrsosxl7bi', 'mchsu5nijbna7jf4ohlkmcysxe', 'tei', 'ghcr.io/huggingface/text-embeddings-inference:cuda-1.9.3@sha256:249a0bc87522bfe2f1012b4d194f0225878f47079115ada3aeb0b1ef257b402a', '["--model-id","/data/bge-m3","--json-output"]', 'missing', 'unless-stopped', '2026-07-31 03:35:10.8127922 +0000 UTC', '2026-07-31 03:35:10.8127922 +0000 UTC');
INSERT INTO version_component (id, version_id, name, image, command_json, pull_policy, restart_policy, created_at, updated_at) VALUES ('kcuvrfydbm37gf6ml74segc5ym', 'mchsu5nijbna7jf4ohlkmcysxe', 'ragflow-cpu', 'infiniflow/ragflow:v0.26.4', '["--enable-adminserver","--init-model-provider-tables"]', 'missing', 'unless-stopped', '2026-07-31 03:35:10.8127922 +0000 UTC', '2026-07-31 03:35:10.8127922 +0000 UTC');
INSERT INTO version_component (id, version_id, name, image, command_json, pull_policy, restart_policy, created_at, updated_at) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'krq3ndmgte4mqx65uaidmeiokm', 'ragflow-cpu', 'infiniflow/ragflow:v0.26.4', '["--enable-adminserver","--init-model-provider-tables"]', 'missing', 'unless-stopped', '2026-07-29 05:44:24.4522011 +0000 UTC', '2026-07-31 04:03:24.0301992 +0000 UTC');
INSERT INTO version_component (id, version_id, name, image, command_json, pull_policy, restart_policy, created_at, updated_at) VALUES ('luc4wuwqrbjaavzchpjxafzeve', 'mchsu5nijbna7jf4ohlkmcysxe', 'minio', 'pgsty/minio:RELEASE.2026-03-25T00-00-00Z', '["server","--console-address",":9001","/data"]', 'missing', 'unless-stopped', '2026-07-31 03:35:10.8127922 +0000 UTC', '2026-07-31 03:35:10.8127922 +0000 UTC');
INSERT INTO version_component (id, version_id, name, image, command_json, pull_policy, restart_policy, created_at, updated_at) VALUES ('mhkgwj47tmbyq5rfokrekeupju', 'krq3ndmgte4mqx65uaidmeiokm', 'minio', 'pgsty/minio:RELEASE.2026-03-25T00-00-00Z', '["server","--console-address",":9001","/data"]', 'missing', 'unless-stopped', '2026-07-29 05:44:24.4522011 +0000 UTC', '2026-07-31 04:03:23.8414084 +0000 UTC');
INSERT INTO version_component (id, version_id, name, image, command_json, pull_policy, restart_policy, created_at, updated_at) VALUES ('pfotzppunsbwtl63eblafazuva', 'mchsu5nijbna7jf4ohlkmcysxe', 'redis', 'valkey/valkey:8', '["sh","-c","exec redis-server --requirepass \"$${REDIS_PASSWORD}\" --maxmemory 128mb --maxmemory-policy allkeys-lru"]', 'missing', 'unless-stopped', '2026-07-31 03:35:10.8127922 +0000 UTC', '2026-07-31 03:35:10.8127922 +0000 UTC');
INSERT INTO version_component (id, version_id, name, image, command_json, pull_policy, restart_policy, created_at, updated_at) VALUES ('tdieyglpa537upvz7vjcc3qgra', 'mchsu5nijbna7jf4ohlkmcysxe', 'mysql', 'mysql:8.0.39', '["--max_connections=1000","--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci","--default-authentication-plugin=mysql_native_password","--tls_version=TLSv1.2,TLSv1.3","--binlog_expire_logs_seconds=604800"]', 'missing', 'unless-stopped', '2026-07-31 03:35:10.8127922 +0000 UTC', '2026-07-31 03:35:10.8127922 +0000 UTC');
INSERT INTO version_component_dependency (component_id, depends_on_name, condition, position) VALUES ('kcuvrfydbm37gf6ml74segc5ym', 'mysql', 'service_healthy', 0);
INSERT INTO version_component_dependency (component_id, depends_on_name, condition, position) VALUES ('kcuvrfydbm37gf6ml74segc5ym', 'redis', 'service_healthy', 1);
INSERT INTO version_component_dependency (component_id, depends_on_name, condition, position) VALUES ('kcuvrfydbm37gf6ml74segc5ym', 'minio', 'service_healthy', 2);
INSERT INTO version_component_dependency (component_id, depends_on_name, condition, position) VALUES ('kcuvrfydbm37gf6ml74segc5ym', 'es01', 'service_healthy', 3);
INSERT INTO version_component_dependency (component_id, depends_on_name, condition, position) VALUES ('kcuvrfydbm37gf6ml74segc5ym', 'tei', 'service_healthy', 4);
INSERT INTO version_component_dependency (component_id, depends_on_name, condition, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'mysql', 'service_healthy', 0);
INSERT INTO version_component_dependency (component_id, depends_on_name, condition, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'redis', 'service_healthy', 1);
INSERT INTO version_component_dependency (component_id, depends_on_name, condition, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'minio', 'service_healthy', 2);
INSERT INTO version_component_dependency (component_id, depends_on_name, condition, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'es01', 'service_healthy', 3);
INSERT INTO version_component_dependency (component_id, depends_on_name, condition, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'tei', 'service_healthy', 4);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('aklwuvbkrshgffcpsvvu3sa2ju', 'ELASTIC_PASSWORD', '${ELASTIC_PASSWORD}', 0);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('aklwuvbkrshgffcpsvvu3sa2ju', 'node.name', 'es01', 1);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('aklwuvbkrshgffcpsvvu3sa2ju', 'bootstrap.memory_lock', 'false', 2);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('aklwuvbkrshgffcpsvvu3sa2ju', 'discovery.type', 'single-node', 3);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('aklwuvbkrshgffcpsvvu3sa2ju', 'xpack.security.enabled', 'true', 4);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('aklwuvbkrshgffcpsvvu3sa2ju', 'xpack.security.http.ssl.enabled', 'false', 5);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('aklwuvbkrshgffcpsvvu3sa2ju', 'xpack.security.transport.ssl.enabled', 'false', 6);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('aklwuvbkrshgffcpsvvu3sa2ju', 'cluster.routing.allocation.disk.watermark.low', '5gb', 7);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('aklwuvbkrshgffcpsvvu3sa2ju', 'cluster.routing.allocation.disk.watermark.high', '3gb', 8);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('aklwuvbkrshgffcpsvvu3sa2ju', 'cluster.routing.allocation.disk.watermark.flood_stage', '2gb', 9);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('bvolgbvcokhtyqgsge4g2dfvva', 'MYSQL_DATABASE', 'rag_flow', 0);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('bvolgbvcokhtyqgsge4g2dfvva', 'MYSQL_ROOT_PASSWORD', '${MYSQL_PASSWORD}', 1);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('bvolgbvcokhtyqgsge4g2dfvva', 'MYSQL_ROOT_HOST', '%', 2);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('cxtiz4ny3i6e2t7s65fhl4g7rm', 'REDIS_PASSWORD', '${REDIS_PASSWORD}', 0);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'ELASTIC_PASSWORD', '${ELASTIC_PASSWORD}', 0);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'node.name', 'es01', 1);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'bootstrap.memory_lock', 'false', 2);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'discovery.type', 'single-node', 3);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'xpack.security.enabled', 'true', 4);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'xpack.security.http.ssl.enabled', 'false', 5);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'xpack.security.transport.ssl.enabled', 'false', 6);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'cluster.routing.allocation.disk.watermark.low', '5gb', 7);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'cluster.routing.allocation.disk.watermark.high', '3gb', 8);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'cluster.routing.allocation.disk.watermark.flood_stage', '2gb', 9);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('kcuvrfydbm37gf6ml74segc5ym', 'DOC_ENGINE', 'elasticsearch', 0);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('kcuvrfydbm37gf6ml74segc5ym', 'DEVICE', 'cpu', 1);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('kcuvrfydbm37gf6ml74segc5ym', 'API_PROXY_SCHEME', 'python', 2);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('kcuvrfydbm37gf6ml74segc5ym', 'TZ', 'Asia/Shanghai', 3);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('kcuvrfydbm37gf6ml74segc5ym', 'MYSQL_HOST', 'mysql', 4);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('kcuvrfydbm37gf6ml74segc5ym', 'MYSQL_PORT', '3306', 5);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('kcuvrfydbm37gf6ml74segc5ym', 'MYSQL_DBNAME', 'rag_flow', 6);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('kcuvrfydbm37gf6ml74segc5ym', 'MYSQL_USER', 'root', 7);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('kcuvrfydbm37gf6ml74segc5ym', 'MYSQL_PASSWORD', '${MYSQL_PASSWORD}', 8);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('kcuvrfydbm37gf6ml74segc5ym', 'MYSQL_MAX_PACKET', '1073741824', 9);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('kcuvrfydbm37gf6ml74segc5ym', 'REDIS_HOST', 'redis', 10);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('kcuvrfydbm37gf6ml74segc5ym', 'REDIS_PASSWORD', '${REDIS_PASSWORD}', 11);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('kcuvrfydbm37gf6ml74segc5ym', 'MINIO_HOST', 'minio', 12);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('kcuvrfydbm37gf6ml74segc5ym', 'MINIO_USER', '${MINIO_USER}', 13);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('kcuvrfydbm37gf6ml74segc5ym', 'MINIO_PASSWORD', '${MINIO_PASSWORD}', 14);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('kcuvrfydbm37gf6ml74segc5ym', 'ES_HOST', 'es01', 15);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('kcuvrfydbm37gf6ml74segc5ym', 'ES_USER', 'elastic', 16);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('kcuvrfydbm37gf6ml74segc5ym', 'ELASTIC_PASSWORD', '${ELASTIC_PASSWORD}', 17);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'DOC_ENGINE', 'elasticsearch', 0);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'DEVICE', 'cpu', 1);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'API_PROXY_SCHEME', 'python', 2);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'TZ', 'Asia/Shanghai', 3);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'MYSQL_HOST', 'mysql', 4);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'MYSQL_PORT', '3306', 5);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'MYSQL_DBNAME', 'rag_flow', 6);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'MYSQL_USER', 'root', 7);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'MYSQL_PASSWORD', '${MYSQL_PASSWORD}', 8);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'MYSQL_MAX_PACKET', '1073741824', 9);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'REDIS_HOST', 'redis', 10);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'REDIS_PASSWORD', '${REDIS_PASSWORD}', 11);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'MINIO_HOST', 'minio', 12);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'MINIO_USER', '${MINIO_USER}', 13);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'MINIO_PASSWORD', '${MINIO_PASSWORD}', 14);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'ES_HOST', 'es01', 15);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'ES_USER', 'elastic', 16);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'ELASTIC_PASSWORD', '${ELASTIC_PASSWORD}', 17);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('luc4wuwqrbjaavzchpjxafzeve', 'MINIO_ROOT_USER', '${MINIO_USER}', 0);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('luc4wuwqrbjaavzchpjxafzeve', 'MINIO_ROOT_PASSWORD', '${MINIO_PASSWORD}', 1);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('mhkgwj47tmbyq5rfokrekeupju', 'MINIO_ROOT_USER', '${MINIO_USER}', 0);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('mhkgwj47tmbyq5rfokrekeupju', 'MINIO_ROOT_PASSWORD', '${MINIO_PASSWORD}', 1);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('pfotzppunsbwtl63eblafazuva', 'REDIS_PASSWORD', '${REDIS_PASSWORD}', 0);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('tdieyglpa537upvz7vjcc3qgra', 'MYSQL_DATABASE', 'rag_flow', 0);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('tdieyglpa537upvz7vjcc3qgra', 'MYSQL_ROOT_PASSWORD', '${MYSQL_PASSWORD}', 1);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('tdieyglpa537upvz7vjcc3qgra', 'MYSQL_ROOT_HOST', '%', 2);
INSERT INTO version_component_healthcheck (component_id, test_mode, test, interval, timeout, retries, start_period, start_interval, disabled) VALUES ('7epg67r6dhovu3v743hnwtxnlu', 'CMD-SHELL', 'curl -fsS http://127.0.0.1:80/health', '30s', '5s', 10, '5m', NULL, 0);
INSERT INTO version_component_healthcheck (component_id, test_mode, test, interval, timeout, retries, start_period, start_interval, disabled) VALUES ('aklwuvbkrshgffcpsvvu3sa2ju', 'CMD-SHELL', 'curl -fsS -u "elastic:$${ELASTIC_PASSWORD}" http://localhost:9200', '10s', '10s', 120, NULL, NULL, 0);
INSERT INTO version_component_healthcheck (component_id, test_mode, test, interval, timeout, retries, start_period, start_interval, disabled) VALUES ('bvolgbvcokhtyqgsge4g2dfvva', 'CMD-SHELL', 'mysqladmin ping -uroot -p"$${MYSQL_ROOT_PASSWORD}"', '10s', '10s', 120, NULL, NULL, 0);
INSERT INTO version_component_healthcheck (component_id, test_mode, test, interval, timeout, retries, start_period, start_interval, disabled) VALUES ('cxtiz4ny3i6e2t7s65fhl4g7rm', 'CMD-SHELL', 'redis-cli -a "$${REDIS_PASSWORD}" ping', '10s', '10s', 120, NULL, NULL, 0);
INSERT INTO version_component_healthcheck (component_id, test_mode, test, interval, timeout, retries, start_period, start_interval, disabled) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'CMD-SHELL', 'curl -fsS -u "elastic:$${ELASTIC_PASSWORD}" http://localhost:9200', '10s', '10s', 120, NULL, NULL, 0);
INSERT INTO version_component_healthcheck (component_id, test_mode, test, interval, timeout, retries, start_period, start_interval, disabled) VALUES ('jblgi2ezvoipwfmclrsosxl7bi', 'CMD-SHELL', 'curl -fsS http://127.0.0.1:80/health', '30s', '5s', 10, '5m', NULL, 0);
INSERT INTO version_component_healthcheck (component_id, test_mode, test, interval, timeout, retries, start_period, start_interval, disabled) VALUES ('kcuvrfydbm37gf6ml74segc5ym', 'CMD', 'curl -fsS http://localhost:80/', '10s', '10s', 120, NULL, NULL, 0);
INSERT INTO version_component_healthcheck (component_id, test_mode, test, interval, timeout, retries, start_period, start_interval, disabled) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'CMD', 'curl -fsS http://localhost:80/', '10s', '10s', 120, NULL, NULL, 0);
INSERT INTO version_component_healthcheck (component_id, test_mode, test, interval, timeout, retries, start_period, start_interval, disabled) VALUES ('luc4wuwqrbjaavzchpjxafzeve', 'CMD', 'curl -fsS http://localhost:9000/minio/health/live', '10s', '10s', 120, NULL, NULL, 0);
INSERT INTO version_component_healthcheck (component_id, test_mode, test, interval, timeout, retries, start_period, start_interval, disabled) VALUES ('mhkgwj47tmbyq5rfokrekeupju', 'CMD', 'curl -fsS http://localhost:9000/minio/health/live', '10s', '10s', 120, NULL, NULL, 0);
INSERT INTO version_component_healthcheck (component_id, test_mode, test, interval, timeout, retries, start_period, start_interval, disabled) VALUES ('pfotzppunsbwtl63eblafazuva', 'CMD-SHELL', 'redis-cli -a "$${REDIS_PASSWORD}" ping', '10s', '10s', 120, NULL, NULL, 0);
INSERT INTO version_component_healthcheck (component_id, test_mode, test, interval, timeout, retries, start_period, start_interval, disabled) VALUES ('tdieyglpa537upvz7vjcc3qgra', 'CMD-SHELL', 'mysqladmin ping -uroot -p"$${MYSQL_ROOT_PASSWORD}"', '10s', '10s', 120, NULL, NULL, 0);
INSERT INTO version_component_mount (component_id, source_type, source, target, read_only, source_is_host_path, content, content_masked, ignore_if_exists, position, mode) VALUES ('5tsyye6bkh2vzt5iqx4mrtxzeq', 'file', '/var/run/docker.sock', '/var/run/docker.sock', 1, 1, NULL, 0, 0, 0, '');
INSERT INTO version_component_mount (component_id, source_type, source, target, read_only, source_is_host_path, content, content_masked, ignore_if_exists, position, mode) VALUES ('5tsyye6bkh2vzt5iqx4mrtxzeq', 'controlled_file', 'traefik.yml', '/etc/traefik/traefik.yml', 0, 0, 'api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik
  rest:
    insecure: true

log:
  level: INFO
', 0, 0, 1, '0644');
INSERT INTO version_component_mount (component_id, source_type, source, target, read_only, source_is_host_path, content, content_masked, ignore_if_exists, position, mode) VALUES ('5tsyye6bkh2vzt5iqx4mrtxzeq', 'controlled_file', 'acme.json', '/letsencrypt/acme.json', 0, 0, '{}', 0, 1, 2, '0600');
INSERT INTO version_component_mount (component_id, source_type, source, target, read_only, source_is_host_path, content, content_masked, ignore_if_exists, position, mode) VALUES ('7epg67r6dhovu3v743hnwtxnlu', 'directory', 'tei/cache', '/data', 0, 0, NULL, 0, 0, 0, '');
INSERT INTO version_component_mount (component_id, source_type, source, target, read_only, source_is_host_path, content, content_masked, ignore_if_exists, position, mode) VALUES ('aklwuvbkrshgffcpsvvu3sa2ju', 'directory', 'es01/data', '/usr/share/elasticsearch/data', 0, 0, NULL, 0, 0, 0, '');
INSERT INTO version_component_mount (component_id, source_type, source, target, read_only, source_is_host_path, content, content_masked, ignore_if_exists, position, mode) VALUES ('bvolgbvcokhtyqgsge4g2dfvva', 'directory', 'mysql/data', '/var/lib/mysql', 0, 0, NULL, 0, 0, 0, '');
INSERT INTO version_component_mount (component_id, source_type, source, target, read_only, source_is_host_path, content, content_masked, ignore_if_exists, position, mode) VALUES ('cxtiz4ny3i6e2t7s65fhl4g7rm', 'directory', 'redis/data', '/data', 0, 0, NULL, 0, 0, 0, '');
INSERT INTO version_component_mount (component_id, source_type, source, target, read_only, source_is_host_path, content, content_masked, ignore_if_exists, position, mode) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'directory', 'es01/data', '/usr/share/elasticsearch/data', 0, 0, NULL, 0, 0, 0, '');
INSERT INTO version_component_mount (component_id, source_type, source, target, read_only, source_is_host_path, content, content_masked, ignore_if_exists, position, mode) VALUES ('jblgi2ezvoipwfmclrsosxl7bi', 'directory', 'tei/cache', '/data', 0, 0, NULL, 0, 0, 0, '');
INSERT INTO version_component_mount (component_id, source_type, source, target, read_only, source_is_host_path, content, content_masked, ignore_if_exists, position, mode) VALUES ('kcuvrfydbm37gf6ml74segc5ym', 'directory', 'ragflow-cpu/logs', '/ragflow/logs', 0, 0, NULL, 0, 0, 0, '');
INSERT INTO version_component_mount (component_id, source_type, source, target, read_only, source_is_host_path, content, content_masked, ignore_if_exists, position, mode) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'directory', 'ragflow-cpu/logs', '/ragflow/logs', 0, 0, NULL, 0, 0, 0, '');
INSERT INTO version_component_mount (component_id, source_type, source, target, read_only, source_is_host_path, content, content_masked, ignore_if_exists, position, mode) VALUES ('luc4wuwqrbjaavzchpjxafzeve', 'directory', 'minio/data', '/data', 0, 0, NULL, 0, 0, 0, '');
INSERT INTO version_component_mount (component_id, source_type, source, target, read_only, source_is_host_path, content, content_masked, ignore_if_exists, position, mode) VALUES ('mhkgwj47tmbyq5rfokrekeupju', 'directory', 'minio/data', '/data', 0, 0, NULL, 0, 0, 0, '');
INSERT INTO version_component_mount (component_id, source_type, source, target, read_only, source_is_host_path, content, content_masked, ignore_if_exists, position, mode) VALUES ('pfotzppunsbwtl63eblafazuva', 'directory', 'redis/data', '/data', 0, 0, NULL, 0, 0, 0, '');
INSERT INTO version_component_mount (component_id, source_type, source, target, read_only, source_is_host_path, content, content_masked, ignore_if_exists, position, mode) VALUES ('tdieyglpa537upvz7vjcc3qgra', 'directory', 'mysql/data', '/var/lib/mysql', 0, 0, NULL, 0, 0, 0, '');
INSERT INTO version_component_port (component_id, host_port, container_port, position) VALUES ('5tsyye6bkh2vzt5iqx4mrtxzeq', 80, 80, 0);
INSERT INTO version_component_port (component_id, host_port, container_port, position) VALUES ('5tsyye6bkh2vzt5iqx4mrtxzeq', 443, 443, 1);
INSERT INTO version_component_port (component_id, host_port, container_port, position) VALUES ('5tsyye6bkh2vzt5iqx4mrtxzeq', 8080, 8080, 2);
INSERT INTO version_component_resource (component_id, limit_cpus, limit_memory, reservation_cpus, reservation_memory) VALUES ('aklwuvbkrshgffcpsvvu3sa2ju', NULL, '8g', NULL, NULL);
INSERT INTO version_component_resource (component_id, limit_cpus, limit_memory, reservation_cpus, reservation_memory) VALUES ('dvwrntepg5g5zktwctdiy76etm', NULL, '8g', NULL, NULL);
INSERT INTO version_component_tmpfs (component_id, target, size_bytes, mode, position) VALUES ('aklwuvbkrshgffcpsvvu3sa2ju', '/tmp', 536870912, '1777', 0);
INSERT INTO version_component_tmpfs (component_id, target, size_bytes, mode, position) VALUES ('dvwrntepg5g5zktwctdiy76etm', '/tmp', 536870912, '1777', 0);
INSERT INTO version_component_ulimit (component_id, name, soft, hard, position) VALUES ('aklwuvbkrshgffcpsvvu3sa2ju', 'memlock', -1, -1, 0);
INSERT INTO version_component_ulimit (component_id, name, soft, hard, position) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'memlock', -1, -1, 0);
INSERT INTO version_component_device (component_id, driver, device_count, capabilities_json, position) VALUES ('jblgi2ezvoipwfmclrsosxl7bi', 'nvidia', 'all', '["gpu"]', 0);
INSERT INTO service (id, application_id, instance_key, version_id, runtime_config_json, status, created_at, updated_at) VALUES ('ys2i2wy27i6c6oee3pxvggkfgu', 'd5bukyuaictz6n3u7ewqbrh32e', 'default', 'krq3ndmgte4mqx65uaidmeiokm', '{"ELASTIC_PASSWORD":"Ykc-DmJbdq6_OKVkmF6lN0U_kJ3CUMtA","MINIO_PASSWORD":"Xvo6vgrhv2omOmDvgJzlvqkg1Xr4Dkab","MINIO_USER":"minio0bbbd3f5b32a68f2","MYSQL_PASSWORD":"VqxSb6TV-NqTx1r9VRk0j4iYnbHGXGTT","REDIS_PASSWORD":"GpgQpGrKUWwNPwP4wtZ1njphHrz9RmFs"}', 'stopped', '2026-07-30 06:36:41.9913994 +0000 UTC', '2026-07-30 06:54:45.9289341 +0000 UTC');
INSERT INTO service (id, application_id, instance_key, version_id, runtime_config_json, status, created_at, updated_at) VALUES ('mtcadekhtypgjmvrashrc3emym', 'n4gn47povet4x7vqrdq4nbiyby', 'default', 'ihv3kbyqegx4m4yojwpp2fqxum', '{}', 'stopped', '2026-07-30 06:32:14.1278022 +0000 UTC', '2026-07-30 06:33:13.8336165 +0000 UTC');
INSERT INTO service_expose (id, service_id, component_name, protocol, container_port, path_prefix, access, listen_port, created_at, updated_at) VALUES ('rcoohkjjichturxyadaap5jhhy', 'ys2i2wy27i6c6oee3pxvggkfgu', 'ragflow-cpu', 'http', 80, NULL, 'local', 9380, '2026-07-30 06:51:29.2742227 +0000 UTC', '2026-07-30 06:51:29.2742227 +0000 UTC');
COMMIT;
PRAGMA foreign_keys = ON;
