syntax = "proto3";

package orbit.api.v1;


import "orbit/application_route.proto";
import "orbit/config_file.proto";
import "orbit/service_config.proto";

message ApplicationExportResp {
  string version = 1;
  string name = 2;
  string code = 3;
  string image_pull_policy = 4;
  bool route_managed = 5;
  repeated ApplicationExportConfigFileResp config_files = 6;
  repeated ApplicationServiceConfigExportResp service_configs = 7;
  repeated ApplicationExportRouteResp routes = 8;
}

message ApplicationImportReq {
  string version = 1;
  string name = 2;
  string code = 3;
  string image_pull_policy = 4;
  bool route_managed = 5;
  repeated ConfigFileReq config_files = 6;
  repeated ApplicationServiceConfigImportReq service_configs = 7;
  repeated ApplicationRouteReq routes = 8;
}
