syntax = "proto3";

package orbit.api.v1;


message ArtifactConfigResp {
  string type = 1;
  string path = 2;
  string name = 3;
}

message ArtifactConfigReq {
  string type = 1;
  string path = 2;
  string name = 3;
}

message ArtifactConfigListReq {
  repeated ArtifactConfigReq items = 1;
}

message BuildStageResp {
  string id = 1;
  string name = 2;
  string image = 3;
  string script = 4;
  repeated ArtifactConfigResp artifacts = 5;
  string description = 6;
  int32 version = 7;
  string created_at = 8;
  string updated_at = 9;
}

message BuildStageCreateReq {
  string name = 1;
  string image = 2;
  string script = 3;
  repeated ArtifactConfigReq artifacts = 4;
  string description = 5;
}

message BuildStageUpdateReq {
  optional string name = 1;
  optional string image = 2;
  optional string script = 3;
  optional ArtifactConfigListReq artifacts = 4;
  optional string description = 5;
}

message BuildStageDuplicateReq {}

message BuildStagePaginatedResp {
  repeated BuildStageResp items = 1;
  int32 total = 2;
  int32 page = 3;
  int32 per_page = 4;
  int32 pages = 5;
}
