syntax = "proto3";

package orbit.api.v1;


import "google/protobuf/struct.proto";

message CreateTaskReq {
  string id = 1;
  string task_type = 2;
  google.protobuf.Value payload = 3;
  string payload_json = 4;
  int32 max_attempts = 5;
}

message PipelineRunExecuteTaskReq {}

message ApplicationDeployTaskReq {}

message ApplicationRestartTaskReq {}

message ApplicationStopTaskReq {}

message TaskResp {
  string id = 1;
  string task_type = 2;
  string payload_json = 3;
  string status = 4;
  int32 attempts = 5;
  int32 max_attempts = 6;
  optional string locked_by = 7;
  optional string locked_at = 8;
  optional string started_at = 9;
  optional string finished_at = 10;
  optional string error_message = 11;
  string created_at = 12;
  string updated_at = 13;
}
