syntax = "proto3";

package orbit.v1.repository;


import "orbit/v1/common/common.proto";

message RepositoryResp {
  string id = 1;
  optional string project_id = 2;
  string name = 3;
  string code = 4;
  string repository_type = 13;
  string repository_url = 5;
  bool has_credential = 6;
  string git_credential_id = 7;
  optional string git_credential_name = 8;
  repeated orbit.v1.common.VariableDeclarationResp variable_declarations = 9;
  string default_branch = 10;
  string created_at = 11;
  string updated_at = 12;
}

message RepositoryCreateReq {
  string name = 1;
  string code = 2;
  string repository_type = 7;
  string repository_url = 3;
  optional string git_credential_id = 4;
  repeated orbit.v1.common.VariableDeclarationReq variable_overrides = 5;
  string default_branch = 6;
}

message RepositoryUpdateReq {
  optional string name = 1;
  optional string repository_type = 6;
  optional string repository_url = 2;
  optional string git_credential_id = 3;
  optional orbit.v1.common.VariableDeclarationListReq variable_overrides = 4;
  optional string default_branch = 5;
}

message RepositoryPaginatedResp {
  repeated RepositoryResp items = 1;
  int32 total = 2;
  int32 page = 3;
  int32 per_page = 4;
  int32 pages = 5;
}
