syntax = "proto3";

package orbit.v1.common;


import "google/protobuf/struct.proto";

message HealthResp {
  string status = 1;
}

message StringListResp {
  repeated string items = 1;
}

message VariableConfigurationResp {
  string description = 1;
  google.protobuf.Value default = 2;
  google.protobuf.Value value = 3;
  bool secret = 4;
  bool editable = 5;
}

message VariableStageBindingResp {
  string stage_id = 1;
  string stage_name = 2;
}

message VariableResp {
  string name = 1;
  string kind = 2;
  string scope = 3;
  optional VariableStageBindingResp stage_binding = 4;
  optional VariableConfigurationResp configuration = 6;
  optional VariableConfigurationResp global_configuration = 7;
  optional VariableConfigurationResp stage_override = 8;
  bool editable = 9;
}

message VariableDeclarationReq {
  string name = 1;
  string description = 2;
  google.protobuf.Value default = 3;
  google.protobuf.Value value = 4;
  bool secret = 5;
  string source = 6;
  bool editable = 7;
  string stage_id = 8;
}

message VariableDeclarationListReq {
  repeated VariableDeclarationReq items = 1;
}

message RawJsonReq {
  google.protobuf.Struct fields = 1;
}
