syntax = "proto3";

package orbit.v1.common;


import "google/protobuf/struct.proto";

message HealthResp {
  string status = 1;
}

message StringListResp {
  repeated string items = 1;
}

message StageVariableDefaultResp {
  string stage_id = 1;
  string stage_name = 2;
  google.protobuf.Value default = 3;
}

message VariableDeclarationResp {
  string name = 1;
  string description = 2;
  google.protobuf.Value default = 3;
  google.protobuf.Value value = 4;
  bool secret = 5;
  string source = 6;
  bool editable = 7;
  repeated StageVariableDefaultResp stage_defaults = 8;
  string stage_id = 9;
  string stage_name = 10;
}

message VariableDeclarationReq {
  string name = 1;
  string description = 2;
  google.protobuf.Value default = 3;
  google.protobuf.Value value = 4;
  bool secret = 5;
  string source = 6;
  bool editable = 7;
  string stage_id = 8;
}

message VariableDeclarationListReq {
  repeated VariableDeclarationReq items = 1;
}

message RawJsonReq {
  google.protobuf.Struct fields = 1;
}
