syntax = "proto3";

package orbit.api.v1;

option go_package = "backend/internal/transport/http/dto/proto/orbit/api/v1;apiv1";

message ApplicationRouteReq {
  string service_name = 1;
  string domain = 2;
  int32 port = 3;
}

message ApplicationRouteResp {
  string id = 1;
  string service_name = 2;
  string domain = 3;
  int32 port = 4;
  string created_at = 5;
  string updated_at = 6;
}

message ApplicationExportRouteResp {
  string service_name = 1;
  string domain = 2;
  int32 port = 3;
}

message ApplicationRouteListResp {
  repeated ApplicationRouteResp items = 1;
}
