syntax = "proto3";

package orbit.api.v1;

option go_package = "backend/internal/transport/http/dto/proto/orbit/api/v1;apiv1";

import "orbit/api/v1/build_stage.proto";
import "orbit/api/v1/common.proto";

message PipelineSnapshotResp {
  string id = 1;
  string template_id = 2;
  string template_name = 3;
  int32 template_version = 4;
  int32 version = 5;
  repeated SnapshotStageResp stages_snapshot = 6;
  repeated VariableDeclarationResp variables_snapshot = 7;
  string created_at = 8;
}

message SnapshotStageResp {
  string name = 1;
  string id = 2;
  string image = 3;
  int32 version = 4;
  repeated string depends_on = 5;
  string script = 6;
  repeated ArtifactConfigResp artifacts = 7;
}
