syntax = "proto3";

package orbit.v1.environment;

message EnvironmentCreateReq {
  string project_id = 1;
  string code = 2;
  string name = 3;
  optional string description = 4;
}

message EnvironmentUpdateReq {
  optional string name = 1;
  optional string description = 2;
}

message EnvironmentResp {
  string id = 1;
  string project_id = 2;
  string code = 3;
  string name = 4;
  optional string description = 5;
  string created_at = 6;
  string updated_at = 7;
}

message EnvironmentPaginatedResp {
  repeated EnvironmentResp items = 1;
  int32 total = 2;
  int32 page = 3;
  int32 per_page = 4;
  int32 pages = 5;
}
