syntax = "proto3";

package orbit.v1.pipeline;


import "orbit/v1/pipeline/pipeline_stage.proto";
import "orbit/v1/common/common.proto";

message PipelineTemplateResp {
  string id = 1;
  string name = 2;
  string description = 3;
  repeated StageOrchestrationResp orchestration = 4;
  repeated PipelineStageResp stages = 5;
  repeated orbit.v1.common.VariableDeclarationResp variable_declarations = 6;
  int32 version = 7;
  string created_at = 8;
  string updated_at = 9;
}

message StageOrchestrationResp {
  string stage_id = 1;
  string stage_name = 2;
  int32 stage_version = 3;
  repeated string depends_on = 4;
  int32 sort_order = 5;
}

message StageOrchestrationReq {
  string stage_id = 1;
  string stage_name = 2;
  int32 stage_version = 3;
  repeated string depends_on = 4;
  int32 sort_order = 5;
}

message TemplateVariableResolveResp {
  repeated orbit.v1.common.VariableDeclarationResp items = 1;
}

message PipelineTemplateCreateReq {
  string name = 1;
  string description = 2;
  repeated orbit.v1.common.VariableDeclarationReq variable_declarations = 3;
}

message StageOrchestrationListReq {
  repeated StageOrchestrationReq items = 1;
}

message PipelineTemplateUpdateReq {
  optional string name = 1;
  optional string description = 2;
  optional StageOrchestrationListReq orchestration = 3;
  optional orbit.v1.common.VariableDeclarationListReq variable_declarations = 4;
}

message TemplateVariableResolveReq {
  repeated StageOrchestrationReq orchestration = 1;
  repeated orbit.v1.common.VariableDeclarationReq variable_declarations = 2;
}

message PipelineTemplateDuplicateReq {}

message PipelineTemplatePaginatedResp {
  repeated PipelineTemplateResp items = 1;
  int32 total = 2;
  int32 page = 3;
  int32 per_page = 4;
  int32 pages = 5;
}
