root = "."
tmp_dir = "tmp/air/api"

[build]
cmd = "go build -o ./tmp/air/api/backend-go.exe ./cmd/backend-go"
entrypoint = "./tmp/air/api/backend-go.exe"
args_bin = ["serve"]
include_ext = ["go", "yaml", "yml", "toml"]
exclude_dir = ["tmp", "bin", "data", "logs", "vendor"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
kill_delay = "500ms"
log = "air-api-build.log"
poll = false
poll_interval = 500
rerun = false
rerun_delay = 500
send_interrupt = true
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = true
time = true

[misc]
clean_on_exit = true
