linters-settings:
  revive:
    rules:
      - name: package-comments
        disabled: true
      - name: exported
        disabled: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused

run:
  timeout: 5m

issues:
  exclude-use-default: false
