syntax = "proto3";

package orbit.v1;

message EnvironmentCreateReq {
  string project_id = 1;
  string code = 2;
  string name = 3;
  optional string description = 4;
  optional string base_domain = 5;
  optional string domain_template = 6;
  optional string default_entrypoint = 7;
  optional string tcp_entrypoint = 8;
  optional string tls_mode = 9;
}

message EnvironmentUpdateReq {
  optional string name = 1;
  optional string description = 2;
  optional string base_domain = 3;
  optional string domain_template = 4;
  optional string default_entrypoint = 5;
  optional string tcp_entrypoint = 6;
  optional string tls_mode = 7;
}

message EnvironmentResp {
  string id = 1;
  string project_id = 2;
  string code = 3;
  string name = 4;
  optional string description = 5;
  string created_at = 6;
  string updated_at = 7;
  string base_domain = 8;
  optional string domain_template = 9;
  string default_entrypoint = 10;
  optional string tcp_entrypoint = 11;
  string tls_mode = 12;
}

message EnvironmentPaginatedResp {
  repeated EnvironmentResp items = 1;
  int32 total = 2;
  int32 page = 3;
  int32 per_page = 4;
  int32 pages = 5;
}
