// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: orbit/api/v1/build_stage.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtifactConfigResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ArtifactConfigResp) Reset() {
	*x = ArtifactConfigResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orbit_api_v1_build_stage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtifactConfigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactConfigResp) ProtoMessage() {}

func (x *ArtifactConfigResp) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_api_v1_build_stage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactConfigResp.ProtoReflect.Descriptor instead.
func (*ArtifactConfigResp) Descriptor() ([]byte, []int) {
	return file_orbit_api_v1_build_stage_proto_rawDescGZIP(), []int{0}
}

func (x *ArtifactConfigResp) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ArtifactConfigResp) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ArtifactConfigResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ArtifactConfigReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ArtifactConfigReq) Reset() {
	*x = ArtifactConfigReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orbit_api_v1_build_stage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtifactConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactConfigReq) ProtoMessage() {}

func (x *ArtifactConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_api_v1_build_stage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactConfigReq.ProtoReflect.Descriptor instead.
func (*ArtifactConfigReq) Descriptor() ([]byte, []int) {
	return file_orbit_api_v1_build_stage_proto_rawDescGZIP(), []int{1}
}

func (x *ArtifactConfigReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ArtifactConfigReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ArtifactConfigReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BuildStageResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image       string                `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Script      string                `protobuf:"bytes,4,opt,name=script,proto3" json:"script,omitempty"`
	Artifacts   []*ArtifactConfigResp `protobuf:"bytes,5,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	Description string                `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Version     int32                 `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt   string                `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   string                `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *BuildStageResp) Reset() {
	*x = BuildStageResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orbit_api_v1_build_stage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildStageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildStageResp) ProtoMessage() {}

func (x *BuildStageResp) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_api_v1_build_stage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildStageResp.ProtoReflect.Descriptor instead.
func (*BuildStageResp) Descriptor() ([]byte, []int) {
	return file_orbit_api_v1_build_stage_proto_rawDescGZIP(), []int{2}
}

func (x *BuildStageResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BuildStageResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BuildStageResp) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *BuildStageResp) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *BuildStageResp) GetArtifacts() []*ArtifactConfigResp {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *BuildStageResp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BuildStageResp) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BuildStageResp) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *BuildStageResp) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type BuildStageCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image       string               `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Script      string               `protobuf:"bytes,3,opt,name=script,proto3" json:"script,omitempty"`
	Artifacts   []*ArtifactConfigReq `protobuf:"bytes,4,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	Description string               `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *BuildStageCreateReq) Reset() {
	*x = BuildStageCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orbit_api_v1_build_stage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildStageCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildStageCreateReq) ProtoMessage() {}

func (x *BuildStageCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_api_v1_build_stage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildStageCreateReq.ProtoReflect.Descriptor instead.
func (*BuildStageCreateReq) Descriptor() ([]byte, []int) {
	return file_orbit_api_v1_build_stage_proto_rawDescGZIP(), []int{3}
}

func (x *BuildStageCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BuildStageCreateReq) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *BuildStageCreateReq) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *BuildStageCreateReq) GetArtifacts() []*ArtifactConfigReq {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *BuildStageCreateReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type BuildStageUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        *string              `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Image       *string              `protobuf:"bytes,2,opt,name=image,proto3,oneof" json:"image,omitempty"`
	Script      *string              `protobuf:"bytes,3,opt,name=script,proto3,oneof" json:"script,omitempty"`
	Artifacts   []*ArtifactConfigReq `protobuf:"bytes,4,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	Description *string              `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
}

func (x *BuildStageUpdateReq) Reset() {
	*x = BuildStageUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orbit_api_v1_build_stage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildStageUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildStageUpdateReq) ProtoMessage() {}

func (x *BuildStageUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_api_v1_build_stage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildStageUpdateReq.ProtoReflect.Descriptor instead.
func (*BuildStageUpdateReq) Descriptor() ([]byte, []int) {
	return file_orbit_api_v1_build_stage_proto_rawDescGZIP(), []int{4}
}

func (x *BuildStageUpdateReq) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *BuildStageUpdateReq) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *BuildStageUpdateReq) GetScript() string {
	if x != nil && x.Script != nil {
		return *x.Script
	}
	return ""
}

func (x *BuildStageUpdateReq) GetArtifacts() []*ArtifactConfigReq {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *BuildStageUpdateReq) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type BuildStagePaginatedResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items   []*BuildStageResp `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total   int32             `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page    int32             `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage int32             `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Pages   int32             `protobuf:"varint,5,opt,name=pages,proto3" json:"pages,omitempty"`
}

func (x *BuildStagePaginatedResp) Reset() {
	*x = BuildStagePaginatedResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orbit_api_v1_build_stage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildStagePaginatedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildStagePaginatedResp) ProtoMessage() {}

func (x *BuildStagePaginatedResp) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_api_v1_build_stage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildStagePaginatedResp.ProtoReflect.Descriptor instead.
func (*BuildStagePaginatedResp) Descriptor() ([]byte, []int) {
	return file_orbit_api_v1_build_stage_proto_rawDescGZIP(), []int{5}
}

func (x *BuildStagePaginatedResp) GetItems() []*BuildStageResp {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BuildStagePaginatedResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BuildStagePaginatedResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *BuildStagePaginatedResp) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *BuildStagePaginatedResp) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

var File_orbit_api_v1_build_stage_proto protoreflect.FileDescriptor

var file_orbit_api_v1_build_stage_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6f, 0x72, 0x62, 0x69, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x6f, 0x72, 0x62, 0x69, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x22, 0x50,
	0x0a, 0x12, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x4f, 0x0a, 0x11, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x9c, 0x02, 0x0a, 0x0e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x3e, 0x0a, 0x09, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61,
	0x63, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6f, 0x72, 0x62, 0x69,
	0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x52, 0x09, 0x61, 0x72, 0x74,
	0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x22, 0xb8, 0x01, 0x0a, 0x13, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x67, 0x65, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x3d, 0x0a, 0x09, 0x61, 0x72,
	0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x6f, 0x72, 0x62, 0x69, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x72, 0x74,
	0x69, 0x66, 0x61, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x52, 0x09,
	0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xfa, 0x01, 0x0a, 0x13,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x67, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x06, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x88, 0x01, 0x01, 0x12, 0x3d, 0x0a, 0x09, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6f, 0x72, 0x62, 0x69, 0x74, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x52, 0x09, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61,
	0x63, 0x74, 0x73, 0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x09, 0x0a,
	0x07, 0x5f, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xa8, 0x01, 0x0a, 0x17, 0x42, 0x75, 0x69,
	0x6c, 0x64, 0x53, 0x74, 0x61, 0x67, 0x65, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f, 0x72, 0x62, 0x69, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x61,
	0x67, 0x65, 0x73, 0x42, 0x3e, 0x5a, 0x3c, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72,
	0x74, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x64, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6f, 0x72, 0x62, 0x69, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x70,
	0x69, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_orbit_api_v1_build_stage_proto_rawDescOnce sync.Once
	file_orbit_api_v1_build_stage_proto_rawDescData = file_orbit_api_v1_build_stage_proto_rawDesc
)

func file_orbit_api_v1_build_stage_proto_rawDescGZIP() []byte {
	file_orbit_api_v1_build_stage_proto_rawDescOnce.Do(func() {
		file_orbit_api_v1_build_stage_proto_rawDescData = protoimpl.X.CompressGZIP(file_orbit_api_v1_build_stage_proto_rawDescData)
	})
	return file_orbit_api_v1_build_stage_proto_rawDescData
}

var file_orbit_api_v1_build_stage_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_orbit_api_v1_build_stage_proto_goTypes = []interface{}{
	(*ArtifactConfigResp)(nil),      // 0: orbit.api.v1.ArtifactConfigResp
	(*ArtifactConfigReq)(nil),       // 1: orbit.api.v1.ArtifactConfigReq
	(*BuildStageResp)(nil),          // 2: orbit.api.v1.BuildStageResp
	(*BuildStageCreateReq)(nil),     // 3: orbit.api.v1.BuildStageCreateReq
	(*BuildStageUpdateReq)(nil),     // 4: orbit.api.v1.BuildStageUpdateReq
	(*BuildStagePaginatedResp)(nil), // 5: orbit.api.v1.BuildStagePaginatedResp
}
var file_orbit_api_v1_build_stage_proto_depIdxs = []int32{
	0, // 0: orbit.api.v1.BuildStageResp.artifacts:type_name -> orbit.api.v1.ArtifactConfigResp
	1, // 1: orbit.api.v1.BuildStageCreateReq.artifacts:type_name -> orbit.api.v1.ArtifactConfigReq
	1, // 2: orbit.api.v1.BuildStageUpdateReq.artifacts:type_name -> orbit.api.v1.ArtifactConfigReq
	2, // 3: orbit.api.v1.BuildStagePaginatedResp.items:type_name -> orbit.api.v1.BuildStageResp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_orbit_api_v1_build_stage_proto_init() }
func file_orbit_api_v1_build_stage_proto_init() {
	if File_orbit_api_v1_build_stage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_orbit_api_v1_build_stage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArtifactConfigResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orbit_api_v1_build_stage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArtifactConfigReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orbit_api_v1_build_stage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildStageResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orbit_api_v1_build_stage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildStageCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orbit_api_v1_build_stage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildStageUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orbit_api_v1_build_stage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildStagePaginatedResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_orbit_api_v1_build_stage_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_orbit_api_v1_build_stage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orbit_api_v1_build_stage_proto_goTypes,
		DependencyIndexes: file_orbit_api_v1_build_stage_proto_depIdxs,
		MessageInfos:      file_orbit_api_v1_build_stage_proto_msgTypes,
	}.Build()
	File_orbit_api_v1_build_stage_proto = out.File
	file_orbit_api_v1_build_stage_proto_rawDesc = nil
	file_orbit_api_v1_build_stage_proto_goTypes = nil
	file_orbit_api_v1_build_stage_proto_depIdxs = nil
}
