// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: orbit/api/v1/credential.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CredentialResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type      string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	CreatedAt string `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *CredentialResp) Reset() {
	*x = CredentialResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orbit_api_v1_credential_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CredentialResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialResp) ProtoMessage() {}

func (x *CredentialResp) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_api_v1_credential_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialResp.ProtoReflect.Descriptor instead.
func (*CredentialResp) Descriptor() ([]byte, []int) {
	return file_orbit_api_v1_credential_proto_rawDescGZIP(), []int{0}
}

func (x *CredentialResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CredentialResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CredentialResp) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CredentialResp) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CredentialDetailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type      string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Data      string `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt string `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *CredentialDetailResp) Reset() {
	*x = CredentialDetailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orbit_api_v1_credential_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CredentialDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialDetailResp) ProtoMessage() {}

func (x *CredentialDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_api_v1_credential_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialDetailResp.ProtoReflect.Descriptor instead.
func (*CredentialDetailResp) Descriptor() ([]byte, []int) {
	return file_orbit_api_v1_credential_proto_rawDescGZIP(), []int{1}
}

func (x *CredentialDetailResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CredentialDetailResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CredentialDetailResp) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CredentialDetailResp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *CredentialDetailResp) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CredentialCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Data string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CredentialCreateReq) Reset() {
	*x = CredentialCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orbit_api_v1_credential_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CredentialCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialCreateReq) ProtoMessage() {}

func (x *CredentialCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_api_v1_credential_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialCreateReq.ProtoReflect.Descriptor instead.
func (*CredentialCreateReq) Descriptor() ([]byte, []int) {
	return file_orbit_api_v1_credential_proto_rawDescGZIP(), []int{2}
}

func (x *CredentialCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CredentialCreateReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CredentialCreateReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type CredentialUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name *string `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Data *string `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
}

func (x *CredentialUpdateReq) Reset() {
	*x = CredentialUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orbit_api_v1_credential_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CredentialUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialUpdateReq) ProtoMessage() {}

func (x *CredentialUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_api_v1_credential_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialUpdateReq.ProtoReflect.Descriptor instead.
func (*CredentialUpdateReq) Descriptor() ([]byte, []int) {
	return file_orbit_api_v1_credential_proto_rawDescGZIP(), []int{3}
}

func (x *CredentialUpdateReq) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CredentialUpdateReq) GetData() string {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return ""
}

type CredentialExportResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type    string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Data    string `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CredentialExportResp) Reset() {
	*x = CredentialExportResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orbit_api_v1_credential_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CredentialExportResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialExportResp) ProtoMessage() {}

func (x *CredentialExportResp) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_api_v1_credential_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialExportResp.ProtoReflect.Descriptor instead.
func (*CredentialExportResp) Descriptor() ([]byte, []int) {
	return file_orbit_api_v1_credential_proto_rawDescGZIP(), []int{4}
}

func (x *CredentialExportResp) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CredentialExportResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CredentialExportResp) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CredentialExportResp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type CredentialImportReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type    string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Data    string `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CredentialImportReq) Reset() {
	*x = CredentialImportReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orbit_api_v1_credential_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CredentialImportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialImportReq) ProtoMessage() {}

func (x *CredentialImportReq) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_api_v1_credential_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialImportReq.ProtoReflect.Descriptor instead.
func (*CredentialImportReq) Descriptor() ([]byte, []int) {
	return file_orbit_api_v1_credential_proto_rawDescGZIP(), []int{5}
}

func (x *CredentialImportReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CredentialImportReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CredentialImportReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CredentialImportReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type CredentialPaginatedResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items   []*CredentialResp `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total   int32             `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page    int32             `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage int32             `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Pages   int32             `protobuf:"varint,5,opt,name=pages,proto3" json:"pages,omitempty"`
}

func (x *CredentialPaginatedResp) Reset() {
	*x = CredentialPaginatedResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orbit_api_v1_credential_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CredentialPaginatedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialPaginatedResp) ProtoMessage() {}

func (x *CredentialPaginatedResp) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_api_v1_credential_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialPaginatedResp.ProtoReflect.Descriptor instead.
func (*CredentialPaginatedResp) Descriptor() ([]byte, []int) {
	return file_orbit_api_v1_credential_proto_rawDescGZIP(), []int{6}
}

func (x *CredentialPaginatedResp) GetItems() []*CredentialResp {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CredentialPaginatedResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CredentialPaginatedResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CredentialPaginatedResp) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *CredentialPaginatedResp) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

var File_orbit_api_v1_credential_proto protoreflect.FileDescriptor

var file_orbit_api_v1_credential_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6f, 0x72, 0x62, 0x69, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x63,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0c, 0x6f, 0x72, 0x62, 0x69, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x22, 0x67, 0x0a,
	0x0e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x81, 0x01, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x51, 0x0a, 0x13, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x59, 0x0a,
	0x13, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42,
	0x07, 0x0a, 0x05, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x22, 0x6c, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x6b, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0xa8, 0x01, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x32, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x6f, 0x72, 0x62, 0x69, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x52, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x42, 0x3e,
	0x5a, 0x3c, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x68, 0x74, 0x74,
	0x70, 0x2f, 0x64, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x72, 0x62, 0x69,
	0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x70, 0x69, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_orbit_api_v1_credential_proto_rawDescOnce sync.Once
	file_orbit_api_v1_credential_proto_rawDescData = file_orbit_api_v1_credential_proto_rawDesc
)

func file_orbit_api_v1_credential_proto_rawDescGZIP() []byte {
	file_orbit_api_v1_credential_proto_rawDescOnce.Do(func() {
		file_orbit_api_v1_credential_proto_rawDescData = protoimpl.X.CompressGZIP(file_orbit_api_v1_credential_proto_rawDescData)
	})
	return file_orbit_api_v1_credential_proto_rawDescData
}

var file_orbit_api_v1_credential_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_orbit_api_v1_credential_proto_goTypes = []interface{}{
	(*CredentialResp)(nil),          // 0: orbit.api.v1.CredentialResp
	(*CredentialDetailResp)(nil),    // 1: orbit.api.v1.CredentialDetailResp
	(*CredentialCreateReq)(nil),     // 2: orbit.api.v1.CredentialCreateReq
	(*CredentialUpdateReq)(nil),     // 3: orbit.api.v1.CredentialUpdateReq
	(*CredentialExportResp)(nil),    // 4: orbit.api.v1.CredentialExportResp
	(*CredentialImportReq)(nil),     // 5: orbit.api.v1.CredentialImportReq
	(*CredentialPaginatedResp)(nil), // 6: orbit.api.v1.CredentialPaginatedResp
}
var file_orbit_api_v1_credential_proto_depIdxs = []int32{
	0, // 0: orbit.api.v1.CredentialPaginatedResp.items:type_name -> orbit.api.v1.CredentialResp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_orbit_api_v1_credential_proto_init() }
func file_orbit_api_v1_credential_proto_init() {
	if File_orbit_api_v1_credential_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_orbit_api_v1_credential_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CredentialResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orbit_api_v1_credential_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CredentialDetailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orbit_api_v1_credential_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CredentialCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orbit_api_v1_credential_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CredentialUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orbit_api_v1_credential_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CredentialExportResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orbit_api_v1_credential_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CredentialImportReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orbit_api_v1_credential_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CredentialPaginatedResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_orbit_api_v1_credential_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_orbit_api_v1_credential_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orbit_api_v1_credential_proto_goTypes,
		DependencyIndexes: file_orbit_api_v1_credential_proto_depIdxs,
		MessageInfos:      file_orbit_api_v1_credential_proto_msgTypes,
	}.Build()
	File_orbit_api_v1_credential_proto = out.File
	file_orbit_api_v1_credential_proto_rawDesc = nil
	file_orbit_api_v1_credential_proto_goTypes = nil
	file_orbit_api_v1_credential_proto_depIdxs = nil
}
