// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: orbit/api/v1/settings.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigItemResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key          string          `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value        *structpb.Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Default      *structpb.Value `protobuf:"bytes,3,opt,name=default,proto3" json:"default,omitempty"`
	IsOverridden bool            `protobuf:"varint,4,opt,name=is_overridden,json=isOverridden,proto3" json:"is_overridden,omitempty"`
	Secret       bool            `protobuf:"varint,5,opt,name=secret,proto3" json:"secret,omitempty"`
	Description  string          `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *ConfigItemResp) Reset() {
	*x = ConfigItemResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orbit_api_v1_settings_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigItemResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigItemResp) ProtoMessage() {}

func (x *ConfigItemResp) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_api_v1_settings_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigItemResp.ProtoReflect.Descriptor instead.
func (*ConfigItemResp) Descriptor() ([]byte, []int) {
	return file_orbit_api_v1_settings_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigItemResp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigItemResp) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ConfigItemResp) GetDefault() *structpb.Value {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *ConfigItemResp) GetIsOverridden() bool {
	if x != nil {
		return x.IsOverridden
	}
	return false
}

func (x *ConfigItemResp) GetSecret() bool {
	if x != nil {
		return x.Secret
	}
	return false
}

func (x *ConfigItemResp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SystemConfigResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ConfigItemResp `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *SystemConfigResp) Reset() {
	*x = SystemConfigResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orbit_api_v1_settings_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemConfigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemConfigResp) ProtoMessage() {}

func (x *SystemConfigResp) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_api_v1_settings_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemConfigResp.ProtoReflect.Descriptor instead.
func (*SystemConfigResp) Descriptor() ([]byte, []int) {
	return file_orbit_api_v1_settings_proto_rawDescGZIP(), []int{1}
}

func (x *SystemConfigResp) GetItems() []*ConfigItemResp {
	if x != nil {
		return x.Items
	}
	return nil
}

type SystemConfigUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string          `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value *structpb.Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SystemConfigUpdateReq) Reset() {
	*x = SystemConfigUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orbit_api_v1_settings_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemConfigUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemConfigUpdateReq) ProtoMessage() {}

func (x *SystemConfigUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_api_v1_settings_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemConfigUpdateReq.ProtoReflect.Descriptor instead.
func (*SystemConfigUpdateReq) Descriptor() ([]byte, []int) {
	return file_orbit_api_v1_settings_proto_rawDescGZIP(), []int{2}
}

func (x *SystemConfigUpdateReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SystemConfigUpdateReq) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type SystemConfigResetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *SystemConfigResetReq) Reset() {
	*x = SystemConfigResetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orbit_api_v1_settings_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemConfigResetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemConfigResetReq) ProtoMessage() {}

func (x *SystemConfigResetReq) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_api_v1_settings_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemConfigResetReq.ProtoReflect.Descriptor instead.
func (*SystemConfigResetReq) Descriptor() ([]byte, []int) {
	return file_orbit_api_v1_settings_proto_rawDescGZIP(), []int{3}
}

func (x *SystemConfigResetReq) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

var File_orbit_api_v1_settings_proto protoreflect.FileDescriptor

var file_orbit_api_v1_settings_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6f, 0x72, 0x62, 0x69, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x73,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6f,
	0x72, 0x62, 0x69, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe1, 0x01, 0x0a, 0x0e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x30, 0x0a, 0x07,
	0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x23,
	0x0a, 0x0d, 0x69, 0x73, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64,
	0x64, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x46, 0x0a,
	0x10, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x32, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x6f, 0x72, 0x62, 0x69, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x57, 0x0a, 0x15, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2a,
	0x0a, 0x14, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65,
	0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x42, 0x3e, 0x5a, 0x3c, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x64, 0x74,
	0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x72, 0x62, 0x69, 0x74, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x70, 0x69, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_orbit_api_v1_settings_proto_rawDescOnce sync.Once
	file_orbit_api_v1_settings_proto_rawDescData = file_orbit_api_v1_settings_proto_rawDesc
)

func file_orbit_api_v1_settings_proto_rawDescGZIP() []byte {
	file_orbit_api_v1_settings_proto_rawDescOnce.Do(func() {
		file_orbit_api_v1_settings_proto_rawDescData = protoimpl.X.CompressGZIP(file_orbit_api_v1_settings_proto_rawDescData)
	})
	return file_orbit_api_v1_settings_proto_rawDescData
}

var file_orbit_api_v1_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_orbit_api_v1_settings_proto_goTypes = []interface{}{
	(*ConfigItemResp)(nil),        // 0: orbit.api.v1.ConfigItemResp
	(*SystemConfigResp)(nil),      // 1: orbit.api.v1.SystemConfigResp
	(*SystemConfigUpdateReq)(nil), // 2: orbit.api.v1.SystemConfigUpdateReq
	(*SystemConfigResetReq)(nil),  // 3: orbit.api.v1.SystemConfigResetReq
	(*structpb.Value)(nil),        // 4: google.protobuf.Value
}
var file_orbit_api_v1_settings_proto_depIdxs = []int32{
	4, // 0: orbit.api.v1.ConfigItemResp.value:type_name -> google.protobuf.Value
	4, // 1: orbit.api.v1.ConfigItemResp.default:type_name -> google.protobuf.Value
	0, // 2: orbit.api.v1.SystemConfigResp.items:type_name -> orbit.api.v1.ConfigItemResp
	4, // 3: orbit.api.v1.SystemConfigUpdateReq.value:type_name -> google.protobuf.Value
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_orbit_api_v1_settings_proto_init() }
func file_orbit_api_v1_settings_proto_init() {
	if File_orbit_api_v1_settings_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_orbit_api_v1_settings_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigItemResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orbit_api_v1_settings_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemConfigResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orbit_api_v1_settings_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemConfigUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orbit_api_v1_settings_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemConfigResetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_orbit_api_v1_settings_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orbit_api_v1_settings_proto_goTypes,
		DependencyIndexes: file_orbit_api_v1_settings_proto_depIdxs,
		MessageInfos:      file_orbit_api_v1_settings_proto_msgTypes,
	}.Build()
	File_orbit_api_v1_settings_proto = out.File
	file_orbit_api_v1_settings_proto_rawDesc = nil
	file_orbit_api_v1_settings_proto_goTypes = nil
	file_orbit_api_v1_settings_proto_depIdxs = nil
}
