#!/usr/bin/env python3
"""Export or import SQLite continuous-delivery control-plane data as SQL."""

from __future__ import annotations

import argparse
import re
import sqlite3
import sys
import tempfile
from pathlib import Path
from typing import Any, Sequence


TABLES = (
    "project",
    "application",
    "version",
    "version_component",
    "version_component_dependency",
    "version_component_env",
    "version_component_healthcheck",
    "version_component_mount",
    "version_component_endpoint",
    "version_component_resource",
    "version_component_tmpfs",
    "version_component_ulimit",
    "version_component_device",
    "gateway_config",
    "service",
    "service_env",
    "service_component",
    "service_component_env",
    "service_component_mount",
    "service_component_resource",
    "service_component_endpoint",
    "route",
)
DELETE_TABLES = tuple(reversed(TABLES))
IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
DEFAULT_DATABASE = Path("data/db/pomelo-orbit.db")


class ExportError(RuntimeError):
    pass


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    subcommands = parser.add_subparsers(dest="command", required=True)

    export = subcommands.add_parser("export", help="write CD control-plane records as SQL")
    export.add_argument("--database", type=Path, default=DEFAULT_DATABASE)
    export.add_argument("--output", type=Path, required=True, help="SQL file written after export checks pass")
    export.add_argument(
        "--relace",
        action="store_true",
        help="prepend DELETE statements so the SQL replaces the exported CD records",
    )

    importer = subcommands.add_parser("import", help="apply an exported CD SQL file")
    importer.add_argument("--database", type=Path, default=DEFAULT_DATABASE)
    importer.add_argument("--input", type=Path, required=True, help="SQL file generated by the export subcommand")

    return parser.parse_args(argv)


def connect_read_only(path: Path) -> sqlite3.Connection:
    if not path.is_file():
        raise ExportError(f"SQLite database does not exist: {path}")
    connection = sqlite3.connect(f"file:{path.as_posix()}?mode=ro", uri=True)
    connection.row_factory = sqlite3.Row
    return connection


def connect_read_write(path: Path) -> sqlite3.Connection:
    if not path.is_file():
        raise ExportError(f"SQLite database does not exist: {path}")
    connection = sqlite3.connect(path)
    connection.execute("PRAGMA foreign_keys = ON")
    return connection


def ensure_database_integrity(connection: sqlite3.Connection) -> None:
    integrity = connection.execute("PRAGMA integrity_check").fetchone()[0]
    if integrity != "ok":
        raise ExportError(f"integrity_check failed: {integrity}")
    foreign_keys = list(connection.execute("PRAGMA foreign_key_check"))
    if foreign_keys:
        raise ExportError(f"foreign_key_check returned {len(foreign_keys)} row(s)")


def quote_identifier(identifier: str) -> str:
    if not IDENTIFIER.fullmatch(identifier):
        raise ExportError(f"invalid SQLite identifier: {identifier}")
    return f'"{identifier}"'


def table_columns(connection: sqlite3.Connection, table: str) -> list[str]:
    rows = list(connection.execute(f"PRAGMA table_info({quote_identifier(table)})"))
    if not rows:
        raise ExportError(f"required table is missing: {table}")
    return [str(row["name"] if isinstance(row, sqlite3.Row) else row[1]) for row in rows]


def table_order_columns(connection: sqlite3.Connection, table: str) -> list[str]:
    rows = list(connection.execute(f"PRAGMA table_info({quote_identifier(table)})"))
    primary_key = sorted(
        (row for row in rows if int(row["pk"] if isinstance(row, sqlite3.Row) else row[5]) > 0),
        key=lambda row: int(row["pk"] if isinstance(row, sqlite3.Row) else row[5]),
    )
    return [str(row["name"] if isinstance(row, sqlite3.Row) else row[1]) for row in primary_key] or [
        str(row["name"] if isinstance(row, sqlite3.Row) else row[1]) for row in rows
    ]


def ensure_required_tables(connection: sqlite3.Connection) -> None:
    for table in TABLES:
        table_columns(connection, table)


def table_rows(connection: sqlite3.Connection, table: str) -> list[dict[str, Any]]:
    columns = table_columns(connection, table)
    order_by = ", ".join(quote_identifier(column) for column in table_order_columns(connection, table))
    query = f"SELECT * FROM {quote_identifier(table)} ORDER BY {order_by}"
    return [dict(row) for row in connection.execute(query)]


def exported_table_rows(connection: sqlite3.Connection) -> dict[str, list[dict[str, Any]]]:
    return {table: table_rows(connection, table) for table in TABLES}


def sql_value(connection: sqlite3.Connection, value: Any) -> str:
    return str(connection.execute("SELECT quote(?)", (value,)).fetchone()[0])


def sql_insert(connection: sqlite3.Connection, table: str, row: dict[str, Any]) -> str:
    columns = list(row)
    if not columns:
        raise ExportError(f"table {table} has no columns")
    values = ", ".join(sql_value(connection, row[column]) for column in columns)
    names = ", ".join(quote_identifier(column) for column in columns)
    return f"INSERT INTO {quote_identifier(table)} ({names}) VALUES ({values});"


def render_sql(
    connection: sqlite3.Connection,
    data: dict[str, list[dict[str, Any]]],
    *,
    relace: bool,
) -> str:
    lines = [
        "-- Continuous-delivery control-plane export. Generated by scripts/cd_baseline.py.",
        "-- This file contains plaintext component and service environment values.",
        "PRAGMA foreign_keys = OFF;",
    ]
    if relace:
        lines.extend(sql_delete(table) for table in DELETE_TABLES)
    for table in TABLES:
        for row in data[table]:
            lines.append(sql_insert(connection, table, row))
    lines.extend(("PRAGMA foreign_keys = ON;", ""))
    return "\n".join(lines)


def sql_delete(table: str) -> str:
    return f"DELETE FROM {quote_identifier(table)};"


def write_output(output: Path, rendered: str) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile("w", encoding="utf-8", newline="\n", dir=output.parent, delete=False) as temporary:
            temporary.write(rendered)
            temporary_path = Path(temporary.name)
        temporary_path.replace(output)
    finally:
        if temporary_path and temporary_path.exists():
            temporary_path.unlink()


def read_input(input_path: Path) -> str:
    if not input_path.is_file():
        raise ExportError(f"SQL input does not exist: {input_path}")
    try:
        content = input_path.read_text(encoding="utf-8")
    except UnicodeDecodeError as error:
        raise ExportError(f"SQL input is not UTF-8 text: {input_path}") from error
    if not content.strip():
        raise ExportError(f"SQL input is empty: {input_path}")
    return content


def import_sql(connection: sqlite3.Connection, sql: str) -> None:
    try:
        # executescript executes statements sequentially; the generated SQL has no transaction.
        connection.executescript(sql)
    except sqlite3.Error as error:
        raise ExportError(f"SQL import failed: {error}") from error
    finally:
        connection.execute("PRAGMA foreign_keys = ON")


def export_command(args: argparse.Namespace) -> Path:
    database = args.database.resolve()
    output = args.output.resolve()
    connection = connect_read_only(database)
    try:
        ensure_database_integrity(connection)
        ensure_required_tables(connection)
        rendered = render_sql(connection, exported_table_rows(connection), relace=args.relace)
    finally:
        connection.close()
    write_output(output, rendered)
    return output


def import_command(args: argparse.Namespace) -> Path:
    database = args.database.resolve()
    input_path = args.input.resolve()
    sql = read_input(input_path)
    connection = connect_read_write(database)
    try:
        ensure_database_integrity(connection)
        ensure_required_tables(connection)
        import_sql(connection, sql)
        ensure_database_integrity(connection)
    finally:
        connection.close()
    return input_path


def main(argv: Sequence[str]) -> int:
    args = parse_args(argv)
    try:
        if args.command == "export":
            output = export_command(args)
            print(f"continuous-delivery SQL written: {output}")
        else:
            input_path = import_command(args)
            print(f"continuous-delivery SQL imported: {input_path}")
    except (ExportError, OSError, sqlite3.Error) as error:
        print(f"continuous-delivery operation blocked: {error}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
