services:
  pomelo-orbit:
    image: pomelo-orbit:20260624
    container_name: pomelo-orbit
    command: ["serve"]
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/pomelo-orbit/data:/app/data
      - /opt/pomelo-orbit/logs:/app/logs
      - /opt/pomelo-orbit/.env:/app/.env
    ports:
      - "9001:80"
    environment:
      - POMELO_ORBIT_JWT__SECRET_KEY=${POMELO_ORBIT_JWT__SECRET_KEY}
    labels:
      - traefik.enable=true
      - traefik.http.routers.pomelo-orbit.rule=Host(`orbit.typing-island.site`)
      - traefik.http.routers.pomelo-orbit.entrypoints=websecure
      - traefik.http.routers.pomelo-orbit.tls=true
      - traefik.http.routers.pomelo-orbit.tls.certresolver=letsencrypt
      - traefik.http.services.pomelo-orbit.loadbalancer.server.port=80

networks:
  traefik:
    external: true
