#!/usr/bin/env python3
"""Export SQLite continuous-delivery control-plane data as SQL INSERT statements."""

from __future__ import annotations

import argparse
import re
import sqlite3
import sys
import tempfile
from pathlib import Path
from typing import Any


TABLES = (
    "project",
    "application",
    "version",
    "version_component",
    "version_component_dependency",
    "version_component_env",
    "version_component_healthcheck",
    "version_component_mount",
    "version_component_endpoint",
    "version_component_resource",
    "version_component_tmpfs",
    "version_component_ulimit",
    "version_component_device",
    "gateway_config",
    "service",
    "service_env",
    "service_component",
    "service_component_env",
    "service_component_mount",
    "service_component_resource",
    "service_component_endpoint",
    "route",
)
IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


class ExportError(RuntimeError):
    pass


def parse_args(argv: list[str]) -> argparse.Namespace:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--database", default=str(root / "data" / "db" / "pomelo-orbit.db"))
    parser.add_argument("--output", required=True, help="SQL file to replace after a successful export")
    parser.add_argument(
        "--replace",
        action="store_true",
        help="replace an existing output file after all export checks pass",
    )
    return parser.parse_args(argv)


def connect_read_only(path: Path) -> sqlite3.Connection:
    if not path.is_file():
        raise ExportError(f"SQLite database does not exist: {path}")
    connection = sqlite3.connect(f"file:{path.as_posix()}?mode=ro", uri=True)
    connection.row_factory = sqlite3.Row
    return connection


def ensure_database_integrity(connection: sqlite3.Connection) -> None:
    integrity = connection.execute("PRAGMA integrity_check").fetchone()[0]
    if integrity != "ok":
        raise ExportError(f"integrity_check failed: {integrity}")
    foreign_keys = list(connection.execute("PRAGMA foreign_key_check"))
    if foreign_keys:
        raise ExportError(f"foreign_key_check returned {len(foreign_keys)} row(s)")


def quote_identifier(identifier: str) -> str:
    if not IDENTIFIER.fullmatch(identifier):
        raise ExportError(f"invalid SQLite identifier: {identifier}")
    return f'"{identifier}"'


def table_columns(connection: sqlite3.Connection, table: str) -> list[str]:
    rows = list(connection.execute(f"PRAGMA table_info({quote_identifier(table)})"))
    if not rows:
        raise ExportError(f"required table is missing: {table}")
    return [str(row["name"]) for row in rows]


def table_order_columns(connection: sqlite3.Connection, table: str) -> list[str]:
    rows = list(connection.execute(f"PRAGMA table_info({quote_identifier(table)})"))
    primary_key = sorted((row for row in rows if int(row["pk"]) > 0), key=lambda row: int(row["pk"]))
    return [str(row["name"]) for row in primary_key] or [str(row["name"]) for row in rows]


def table_rows(connection: sqlite3.Connection, table: str) -> list[dict[str, Any]]:
    columns = table_columns(connection, table)
    order_by = ", ".join(quote_identifier(column) for column in table_order_columns(connection, table))
    query = f"SELECT * FROM {quote_identifier(table)} ORDER BY {order_by}"
    return [dict(row) for row in connection.execute(query)]


def exported_table_rows(connection: sqlite3.Connection) -> dict[str, list[dict[str, Any]]]:
    return {table: table_rows(connection, table) for table in TABLES}


def sql_value(connection: sqlite3.Connection, value: Any) -> str:
    return str(connection.execute("SELECT quote(?)", (value,)).fetchone()[0])


def sql_insert(connection: sqlite3.Connection, table: str, row: dict[str, Any]) -> str:
    columns = list(row)
    if not columns:
        raise ExportError(f"table {table} has no columns")
    values = ", ".join(sql_value(connection, row[column]) for column in columns)
    names = ", ".join(quote_identifier(column) for column in columns)
    return f"INSERT INTO {quote_identifier(table)} ({names}) VALUES ({values});"


def render_sql(connection: sqlite3.Connection, data: dict[str, list[dict[str, Any]]]) -> str:
    lines = [
        "-- Continuous-delivery control-plane export. Generated by scripts/export_cd_baseline.py.",
        "PRAGMA foreign_keys = ON;",
        "BEGIN;",
        "PRAGMA defer_foreign_keys = ON;",
    ]
    for table in TABLES:
        for row in data[table]:
            lines.append(sql_insert(connection, table, row))
    lines.extend(("COMMIT;", "PRAGMA foreign_keys = ON;", ""))
    return "\n".join(lines)


def write_output(output: Path, rendered: str, *, replace: bool) -> None:
    if output.exists() and not replace:
        raise ExportError(f"output already exists; pass --replace to overwrite: {output}")
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile("w", encoding="utf-8", newline="\n", dir=output.parent, delete=False) as temporary:
            temporary.write(rendered)
            temporary_path = Path(temporary.name)
        temporary_path.replace(output)
    finally:
        if temporary_path and temporary_path.exists():
            temporary_path.unlink()


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    try:
        with connect_read_only(Path(args.database).resolve()) as connection:
            ensure_database_integrity(connection)
            rendered = render_sql(connection, exported_table_rows(connection))
        write_output(Path(args.output).resolve(), rendered, replace=args.replace)
    except (ExportError, OSError, sqlite3.Error) as error:
        print(f"continuous-delivery export blocked: {error}", file=sys.stderr)
        return 2
    print(f"continuous-delivery SQL written: {Path(args.output).resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
