-- RAGFlow bundled topology export from the current development SQLite database.
-- Includes the existing Application, Version, Component, Service, and ServiceExpose rows.

BEGIN TRANSACTION;
INSERT INTO project (id, name, code, created_at, updated_at, is_active) VALUES ('01KRRKK0K3T519ZQZES3M4QA9Z', '默认项目', 'default', '2024-03-16T00:00:00Z', '2024-03-16T00:00:00Z', 1);
INSERT INTO application (id, name, code, kind, image_pull_policy, created_at, updated_at, project_id) VALUES ('d5bukyuaictz6n3u7ewqbrh32e', 'RAGFlow', 'ragflow', 'standard', 'missing', '2026-07-29 05:43:13.6131134 +0000 UTC', '2026-07-29 05:43:13.6131134 +0000 UTC', '01KRRKK0K3T519ZQZES3M4QA9Z');
INSERT INTO version (id, application_id, label, status, created_from_version_id, note, component_summary, created_at, updated_at) VALUES ('krq3ndmgte4mqx65uaidmeiokm', 'd5bukyuaictz6n3u7ewqbrh32e', 'ragflow-v0.26.4', 'unpublished', NULL, NULL, 'es01, minio, mysql, ragflow-cpu, redis', '2026-07-29 05:44:24.4516542 +0000 UTC', '2026-07-29 08:32:46.1699854 +0000 UTC');
INSERT INTO version_component (id, version_id, name, image, command_json, pull_policy, restart_policy, created_at, updated_at) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'krq3ndmgte4mqx65uaidmeiokm', 'es01', 'elasticsearch:8.11.3', '[]', NULL, 'unless-stopped', '2026-07-29 05:44:24.4522011 +0000 UTC', '2026-07-29 08:32:46.1694806 +0000 UTC');
INSERT INTO version_component (id, version_id, name, image, command_json, pull_policy, restart_policy, created_at, updated_at) VALUES ('mhkgwj47tmbyq5rfokrekeupju', 'krq3ndmgte4mqx65uaidmeiokm', 'minio', 'pgsty/minio:RELEASE.2026-03-25T00-00-00Z', '["server","--console-address",":9001","/data"]', NULL, 'unless-stopped', '2026-07-29 05:44:24.4522011 +0000 UTC', '2026-07-29 05:44:24.4522011 +0000 UTC');
INSERT INTO version_component (id, version_id, name, image, command_json, pull_policy, restart_policy, created_at, updated_at) VALUES ('bvolgbvcokhtyqgsge4g2dfvva', 'krq3ndmgte4mqx65uaidmeiokm', 'mysql', 'mysql:8.0.39', '["--max_connections=1000","--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci","--default-authentication-plugin=mysql_native_password","--tls_version=TLSv1.2,TLSv1.3","--binlog_expire_logs_seconds=604800"]', NULL, 'unless-stopped', '2026-07-29 05:44:24.4522011 +0000 UTC', '2026-07-29 05:44:24.4522011 +0000 UTC');
INSERT INTO version_component (id, version_id, name, image, command_json, pull_policy, restart_policy, created_at, updated_at) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'krq3ndmgte4mqx65uaidmeiokm', 'ragflow-cpu', 'infiniflow/ragflow:v0.26.4', '["--enable-adminserver","--init-model-provider-tables"]', NULL, 'unless-stopped', '2026-07-29 05:44:24.4522011 +0000 UTC', '2026-07-29 06:01:56.1077245 +0000 UTC');
INSERT INTO version_component (id, version_id, name, image, command_json, pull_policy, restart_policy, created_at, updated_at) VALUES ('cxtiz4ny3i6e2t7s65fhl4g7rm', 'krq3ndmgte4mqx65uaidmeiokm', 'redis', 'valkey/valkey:8', '["sh","-c","exec redis-server --requirepass \"$${REDIS_PASSWORD}\" --maxmemory 128mb --maxmemory-policy allkeys-lru"]', NULL, 'unless-stopped', '2026-07-29 05:44:24.4522011 +0000 UTC', '2026-07-29 05:44:24.4522011 +0000 UTC');
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'ELASTIC_PASSWORD', '${ELASTIC_PASSWORD}', 0);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'node.name', 'es01', 1);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'bootstrap.memory_lock', 'false', 2);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'discovery.type', 'single-node', 3);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'xpack.security.enabled', 'true', 4);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'xpack.security.http.ssl.enabled', 'false', 5);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'xpack.security.transport.ssl.enabled', 'false', 6);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'cluster.routing.allocation.disk.watermark.low', '5gb', 7);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'cluster.routing.allocation.disk.watermark.high', '3gb', 8);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'cluster.routing.allocation.disk.watermark.flood_stage', '2gb', 9);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('mhkgwj47tmbyq5rfokrekeupju', 'MINIO_ROOT_USER', '${MINIO_USER}', 0);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('mhkgwj47tmbyq5rfokrekeupju', 'MINIO_ROOT_PASSWORD', '${MINIO_PASSWORD}', 1);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('bvolgbvcokhtyqgsge4g2dfvva', 'MYSQL_DATABASE', 'rag_flow', 0);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('bvolgbvcokhtyqgsge4g2dfvva', 'MYSQL_ROOT_PASSWORD', '${MYSQL_PASSWORD}', 1);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('bvolgbvcokhtyqgsge4g2dfvva', 'MYSQL_ROOT_HOST', '%', 2);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'DOC_ENGINE', 'elasticsearch', 0);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'DEVICE', 'cpu', 1);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'API_PROXY_SCHEME', 'python', 2);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'TZ', 'Asia/Shanghai', 3);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'MYSQL_HOST', 'mysql', 4);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'MYSQL_PORT', '3306', 5);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'MYSQL_DBNAME', 'rag_flow', 6);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'MYSQL_USER', 'root', 7);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'MYSQL_PASSWORD', '${MYSQL_PASSWORD}', 8);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'MYSQL_MAX_PACKET', '1073741824', 9);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'REDIS_HOST', 'redis', 10);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'REDIS_PASSWORD', '${REDIS_PASSWORD}', 11);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'MINIO_HOST', 'minio', 12);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'MINIO_USER', '${MINIO_USER}', 13);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'MINIO_PASSWORD', '${MINIO_PASSWORD}', 14);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'ES_HOST', 'es01', 15);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'ES_USER', 'elastic', 16);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'ELASTIC_PASSWORD', '${ELASTIC_PASSWORD}', 17);
INSERT INTO version_component_env (component_id, env_key, value, position) VALUES ('cxtiz4ny3i6e2t7s65fhl4g7rm', 'REDIS_PASSWORD', '${REDIS_PASSWORD}', 0);
INSERT INTO version_component_healthcheck (component_id, test_mode, test, interval, timeout, retries, start_period, start_interval, disabled) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'CMD-SHELL', 'curl -fsS -u "elastic:$${ELASTIC_PASSWORD}" http://localhost:9200', '10s', '10s', 120, NULL, NULL, 0);
INSERT INTO version_component_healthcheck (component_id, test_mode, test, interval, timeout, retries, start_period, start_interval, disabled) VALUES ('mhkgwj47tmbyq5rfokrekeupju', 'CMD', 'curl -fsS http://localhost:9000/minio/health/live', '10s', '10s', 120, NULL, NULL, 0);
INSERT INTO version_component_healthcheck (component_id, test_mode, test, interval, timeout, retries, start_period, start_interval, disabled) VALUES ('bvolgbvcokhtyqgsge4g2dfvva', 'CMD-SHELL', 'mysqladmin ping -uroot -p"$${MYSQL_ROOT_PASSWORD}"', '10s', '10s', 120, NULL, NULL, 0);
INSERT INTO version_component_healthcheck (component_id, test_mode, test, interval, timeout, retries, start_period, start_interval, disabled) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'CMD', 'curl -fsS http://localhost:80/', '10s', '10s', 120, NULL, NULL, 0);
INSERT INTO version_component_healthcheck (component_id, test_mode, test, interval, timeout, retries, start_period, start_interval, disabled) VALUES ('cxtiz4ny3i6e2t7s65fhl4g7rm', 'CMD-SHELL', 'redis-cli -a "$${REDIS_PASSWORD}" ping', '10s', '10s', 120, NULL, NULL, 0);
INSERT INTO version_component_mount (component_id, source_type, source, target, read_only, source_is_host_path, content, content_masked, ignore_if_exists, position, mode) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'directory', 'es01/data', '/usr/share/elasticsearch/data', 0, 0, NULL, 0, 0, 0, '');
INSERT INTO version_component_mount (component_id, source_type, source, target, read_only, source_is_host_path, content, content_masked, ignore_if_exists, position, mode) VALUES ('mhkgwj47tmbyq5rfokrekeupju', 'directory', 'minio/data', '/data', 0, 0, NULL, 0, 0, 0, '');
INSERT INTO version_component_mount (component_id, source_type, source, target, read_only, source_is_host_path, content, content_masked, ignore_if_exists, position, mode) VALUES ('bvolgbvcokhtyqgsge4g2dfvva', 'directory', 'mysql/data', '/var/lib/mysql', 0, 0, NULL, 0, 0, 0, '');
INSERT INTO version_component_mount (component_id, source_type, source, target, read_only, source_is_host_path, content, content_masked, ignore_if_exists, position, mode) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'directory', 'ragflow-cpu/logs', '/ragflow/logs', 0, 0, NULL, 0, 0, 0, '');
INSERT INTO version_component_mount (component_id, source_type, source, target, read_only, source_is_host_path, content, content_masked, ignore_if_exists, position, mode) VALUES ('cxtiz4ny3i6e2t7s65fhl4g7rm', 'directory', 'redis/data', '/data', 0, 0, NULL, 0, 0, 0, '');
INSERT INTO version_component_dependency (component_id, depends_on_name, condition, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'mysql', 'service_healthy', 0);
INSERT INTO version_component_dependency (component_id, depends_on_name, condition, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'redis', 'service_healthy', 1);
INSERT INTO version_component_dependency (component_id, depends_on_name, condition, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'minio', 'service_healthy', 2);
INSERT INTO version_component_dependency (component_id, depends_on_name, condition, position) VALUES ('ktgbpgnu2xgo3xhpujfwkzlkc4', 'es01', 'service_healthy', 3);
INSERT INTO version_component_resource (component_id, limit_cpus, limit_memory, reservation_cpus, reservation_memory) VALUES ('dvwrntepg5g5zktwctdiy76etm', NULL, '8g', NULL, NULL);
INSERT INTO version_component_tmpfs (component_id, target, size_bytes, mode, position) VALUES ('dvwrntepg5g5zktwctdiy76etm', '/tmp', 536870912, '1777', 0);
INSERT INTO version_component_ulimit (component_id, name, soft, hard, position) VALUES ('dvwrntepg5g5zktwctdiy76etm', 'memlock', -1, -1, 0);
INSERT INTO service (id, application_id, instance_key, version_id, runtime_config_json, status, created_at, updated_at) VALUES ('ys2i2wy27i6c6oee3pxvggkfgu', 'd5bukyuaictz6n3u7ewqbrh32e', 'default', 'krq3ndmgte4mqx65uaidmeiokm', '{"ELASTIC_PASSWORD":"3b39f4b13409d5d4794e17348031e2686b171a84cd413f649dca09f486e8fe11","MINIO_PASSWORD":"3397ffbd06d5502b5978ac22a7dd8b23928fc4e60c776dfdee1c17b5d22018d3","MINIO_USER":"ragflowc3c1aee18d6ef8b932b0","MYSQL_PASSWORD":"79e8ec8a18c727d1cc64ef8d5f0271a89f1bcf5da6f71c9f72e53e400ccc3d46","REDIS_PASSWORD":"77b5e57a5de77a387cdf26982a000c8bc1734b1cb2eb24564cd6733901967ab0"}', 'running', '2026-07-30 06:36:41.9913994 +0000 UTC', '2026-07-30 06:54:45.9289341 +0000 UTC');
INSERT INTO service_expose (id, service_id, component_name, protocol, container_port, path_prefix, access, listen_port, created_at, updated_at) VALUES ('rcoohkjjichturxyadaap5jhhy', 'ys2i2wy27i6c6oee3pxvggkfgu', 'ragflow-cpu', 'http', 80, NULL, 'local', 9380, '2026-07-30 06:51:29.2742227 +0000 UTC', '2026-07-30 06:51:29.2742227 +0000 UTC');

COMMIT;
